[tool.pylint.MASTER]
load-plugins = ["pylint_django"]
django-settings-module = "config.settings"

[tool.pylint.MESSAGE_CONTROL]
disable = [
    "C0111",  # missing-docstring
    "R0903",  # too-few-public-methods
    "R0901",  # too-many-ancestors
    "W0613",  # unused-argument
    "C0103",  # invalid-name
]

[tool.pylint.FORMAT]
max-line-length = 88 